#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

. `dirname ${0}`/bigtop.bom

HIVE_MAVEN_OPTS=" -Dhbase.version=$HBASE_VERSION \
-Dzookeeper.version=$ZOOKEEPER_VERSION \
-Dhadoop.version=$HADOOP_VERSION \
-DskipTests \
-Dtez.version=${TEZ_VERSION} \
-Dspark.version=${SPARK_VERSION} \
-Dscala.binary.version=${SCALA_VERSION%.*} \
-Dscala.version=${SCALA_VERSION} \
-Dguava.version=27.0-jre
"

# Include common Maven Deployment logic
. $(dirname ${0})/maven_deploy.sh

# create com.google.protobuf:protoc artifact with local protoc built by toolchain
# for non-x86 platforms
if [ $HOSTTYPE = "powerpc64le" ] ; then
  mvn install:install-file -DgroupId=com.google.protobuf -DartifactId=protoc -Dversion=2.5.0 \
    -Dclassifier=linux-ppcle_64 -Dpackaging=exe -Dfile=/usr/local/protobuf-2.5.0/bin/protoc
elif [ $HOSTTYPE = "aarch64" ] ; then
  mvn install:install-file -DgroupId=com.google.protobuf -DartifactId=protoc -Dversion=2.5.0 \
    -Dclassifier=linux-aarch_64 -Dpackaging=exe -Dfile=/usr/local/protobuf-2.5.0/bin/protoc
fi
mvn ${HIVE_MAVEN_OPTS} clean install ${EXTRA_GOALS} -Pdist "$@"

mkdir -p build/dist
tar -C build/dist --strip-components=1 -xzf packaging/target/apache-hive-${HIVE_VERSION}-bin.tar.gz

# HIVE-13177
sed -i "s#jdbcStandaloneJarPath=\`ls \${HIVE_LIB}/hive-jdbc-\*-standalone.jar\`#jdbcStandaloneJarPath=#" build/dist/bin/ext/beeline.sh
