#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex
. $(dirname $0)/bigtop.bom

for dir in stacks/BIGTOP common-services; do
    mkdir -p $(dirname $0)/bgtp-ambari-mpack/src/main/resources/$dir/
    cp -r ambari-server/src/main/resources/$dir/* $(dirname $0)/bgtp-ambari-mpack/src/main/resources/$dir/
done

# FIXME: install-mpack fails because only directories should exists below common-services dir.
rm -f $(dirname $0)/bgtp-ambari-mpack/src/main/resources/common-services/README.txt

cp -r $(dirname $0)/bgtp-ambari-mpack contrib/management-packs/
cd contrib/management-packs/bgtp-ambari-mpack
mvn versions:set -DnewVersion=${BIGTOP_AMBARI_MPACK_VERSION_WITH_RELEASE}
mvn clean package -DskipTests -Drat.skip
