#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

. `dirname $0`/bigtop.bom

MAVEN_OPTS="-DskipTests=true $DO_MAVEN_DEPLOY"
mvn -Dhadoop.version=${HADOOP_VERSION} -Dzookeeper.version=${ZOOKEEPER_VERSION} package -P assemble $MAVEN_OPTS
mkdir -p lib
mv server/native/target/accumulo-native-*.tar.gz lib/accumulo-native.tar.gz
./bin/build_native_library.sh

ALL_FILES=`ls`
mkdir -p accumulo-${ACCUMULO_VERSION} build
cp -r ${ALL_FILES} accumulo-${ACCUMULO_VERSION}/
tar czf build/accumulo-${ACCUMULO_VERSION}.tar.gz accumulo-${ACCUMULO_VERSION}

