#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex
. `dirname $0`/bigtop.bom

export _JAVA_OPTIONS="-Xmx2048m -Djava.awt.headless=true"

# these two repos haven updated to accpet https access only
sed -i "s|http://download.java.net|https://download.java.net|g" pom.xml
sed -i "s|http://repo.spring.io|https://repo.spring.io|g" pom.xml

mvn clean package -DskipTests -Drat.skip

(cd contrib/management-packs/odpi-ambari-mpack ; mvn clean package -DskipTests -Drat.skip)
(cd contrib/management-packs/bgtp-ambari-mpack ; mvn clean package -DskipTests -Drat.skip)
