#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

#specify the verion of python for openEuler
. /etc/os-release
OS="$ID"
if [ "${OS}" = "openEuler" ]; then
  sed -i 's|python setup.py build|python2 setup.py build|g'  gpMgmt/bin/Makefile
  sed -i 's|python gpconfig_modules|python2 gpconfig_modules|g' gpMgmt/bin/Makefile
fi

PYTHON=/usr/bin/python3 ./configure --prefix=$1 --with-python --with-libxml --with-gssapi --disable-orca CFLAGS='-fcommon -Wno-implicit-fallthrough'
