.\" Licensed to the Apache Software Foundation (ASF) under one or more
.\" contributor license agreements.  See the NOTICE file distributed with
.\" this work for additional information regarding copyright ownership.
.\" The ASF licenses this file to You under the Apache License, Version 2.0
.\" (the "License"); you may not use this file except in compliance with
.\" the License.  You may obtain a copy of the License at
.\"
.\"     http://www.apache.org/licenses/LICENSE-2.0
.\"
.\" Unless required by applicable law or agreed to in writing, software
.\" distributed under the License is distributed on an "AS IS" BASIS,
.\" WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
.\" See the License for the specific language governing permissions and
.\" limitations under the License.
.\"
.\" Process this file with
.\" groff -man -Tascii oozie.1
.\"
.TH oozie 1

.SH NAME
Oozie \- Oozie command line client tool

.SH SYNOPSIS

.B oozie
subcommand [options]

.SH DESCRIPTION

Apache Oozie Workflow Scheduler for Hadoop is a workflow/coordination
service to manage Apache Hadoop jobs. Oozie Workflow jobs are Directed
Acyclical Graphs (DAGs) of actions, actions are typically Hadoop jobs
(MapReduce, Streaming, Pipes, Pig, Hive, Sqoop, etc). Oozie Coordinator
jobs trigger recurrent Workflow jobs based on time (frequency) and data
availability. Oozie Bundle jobs are sets of Coordinator jobs managed as a
single job. Oozie is an extensible, scalable and data-aware service to
to orchestrate dependencies among jobs running on Hadoop.

For more information about Apache Oozie project and detailed documentation,
visit

       http://oozie.apache.org/

Run 'oozie help' to access the built-in tool documentation.
