#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

. `dirname $0`/bigtop.bom

export MAVEN_OPTS="-Xmx512m -XX:MaxPermSize=128m"

mvn -DskipTests -Dcrunch.platform=2           \
    -Dhadoop.version=$HADOOP_VERSION          \
    -Dhbase.version=$HBASE_VERSION            \
    -Dspark.version=$SPARK_VERSION            \
    -Papache-release clean site:site package "$@"

rm -rf build
mkdir build
tar --strip-component=1 -C build -xzvf crunch-dist/target/apache-crunch-*-bin.tar.gz
cp -r target/site build
