#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

. `dirname $0`/bigtop.bom

mvn clean install -DskipTests

mkdir -p build/presto-${PRESTO_VERSION}
mkdir -p build/presto-${PRESTO_VERSION}/docs

# Server
tar -C build/presto-${PRESTO_VERSION} --strip-components=1 -xzf presto-server/target/presto-server-${PRESTO_VERSION}.tar.gz
# CLI
cp -ra presto-cli/target/presto-cli-${PRESTO_VERSION}-executable.jar build/presto-${PRESTO_VERSION}/bin/presto
# Docs
cp -ra presto-docs/target/html/* build/presto-${PRESTO_VERSION}/docs/
# JDBC
cp -ra presto-jdbc/target/presto-jdbc-${PRESTO_VERSION}.jar build/presto-${PRESTO_VERSION}/lib/
