#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

. `dirname ${0}`/bigtop.bom

mvn versions:set -DnewVersion=${ZOOKEEPER_VERSION}.${VDP_RELEASE}
mvn clean install -DskipTests -Pfull-build  -Dmaven.repo.local="/var/lib/jenkins/murali/repository"
(cd zookeeper-contrib/zookeeper-contrib-rest ; mvn dependency:copy-dependencies -Dmaven.repo.local="/var/lib/jenkins/murali/repository")

mkdir -p build
(cd build ; tar --strip-components=1 -xzvf  ../zookeeper-assembly/target/apache-zookeeper-${ZOOKEEPER_VERSION}.${VDP_RELEASE}-bin.tar.gz)

mkdir -p build/native
cp -R zookeeper-client/zookeeper-client-c/target/c/include build/native/
cp -R zookeeper-client/zookeeper-client-c/target/c/lib build/native/
cp -R zookeeper-client/zookeeper-client-c/target/c/bin build/native/

mkdir -p build/contrib/rest
mkdir -p build/contrib/rest/lib
cp -R zookeeper-contrib/zookeeper-contrib-rest/conf build/contrib/rest/
cp zookeeper-contrib/zookeeper-contrib-rest/target/zookeeper-contrib-rest-${ZOOKEEPER_VERSION}.${VDP_RELEASE}.jar build/contrib/rest/
cp zookeeper-contrib/zookeeper-contrib-rest/target/dependency/* build/contrib/rest/lib/
