#!/bin/bash
# This is a modification of the standard Spark executor script to run
# with Standalone executor backend
# TODO: we are likely need to add YARN executor later
FWDIR="`dirname $0`"
echo "Running spark-executor with framework dir = $FWDIR"
exec $FWDIR/run spark.executor.StandaloneExecutorBackend
