#!/bin/bash

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

if hdfs dfs -stat /tmp/input/ &> /dev/null; then
    hdfs dfs -rm -r -skipTrash /tmp/input/ || true
fi

hdfs dfs -mkdir /tmp/input/
hdfs dfs -put resources/links-converted.txt /tmp/input/
hdfs dfs -put resources/users.txt /tmp/input/

if hdfs dfs -stat temp &> /dev/null; then
    hdfs dfs -rm -r -skipTrash temp || true
fi
if hdfs dfs -stat output &> /dev/null; then
    hdfs dfs -rm -r -skipTrash output || true
fi

hadoop jar /usr/lib/mahout/mahout-mr-*-job.jar org.apache.mahout.cf.taste.hadoop.item.RecommenderJob -Dmapred.input.dir=/tmp/input/links-converted.txt -Dmapred.output.dir=output --usersFile /tmp/input/users.txt --booleanData -s SIMILARITY_LOGLIKELIHOOD
