#!/usr/local/sbin/charm-env bash

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

if ! charms.reactive is_state 'mahout.installed'; then
    action-fail 'Mahout is not yet ready'
    exit
fi

# create dir to store results
RUN=`date +%s`
RESULT_DIR=/opt/mahout-smoke-results
RESULT_LOG=${RESULT_DIR}/${RUN}.log
mkdir -p ${RESULT_DIR}
chown -R ubuntu:ubuntu ${RESULT_DIR}

# hdfs dirs
MAHOUT_SMOKE="/tmp/mahout-smoke"
MAHOUT_INPUT="${MAHOUT_SMOKE}/input"
MAHOUT_OUTPUT="${MAHOUT_SMOKE}/output"

# remove any previous smoke test run. must be run as ubuntu, since that user
# owns the hdfs space
su - ubuntu -c "hadoop fs -rm -f -r -skipTrash ${MAHOUT_SMOKE}"
su - ubuntu -c "hadoop fs -rm -f -r -skipTrash temp"

echo 'running mahout smoke-test as the ubuntu user'
# NB: Escaped envars in the block below (e.g., \${CHARM_DIR}) come from
# the environment while non-escaped vars (e.g., ${MAHOUT_INPUT}) come from
# this outer scope.
su ubuntu << EOF
set -x
. /etc/default/hadoop
. /etc/environment

# setup our smoke test input
hdfs dfs -mkdir -p ${MAHOUT_INPUT}
hdfs dfs -put \${CHARM_DIR}/resources/links-converted.txt ${MAHOUT_INPUT}
hdfs dfs -put \${CHARM_DIR}/resources/users.txt ${MAHOUT_INPUT}

hadoop jar /usr/lib/mahout/mahout-mr-*-job.jar \
  org.apache.mahout.cf.taste.hadoop.item.RecommenderJob \
  -Dmapreduce.input.fileinputformat.inputdir=${MAHOUT_INPUT}/links-converted.txt \
  -Dmapred.output.dir=${MAHOUT_OUTPUT} \
  --usersFile ${MAHOUT_INPUT}/users.txt \
  --booleanData \
  -s SIMILARITY_LOGLIKELIHOOD 2>&1 | tee -a ${RESULT_LOG}
EOF
echo 'mahout smoke-test complete'
action-set outcome="success"
