apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: bigtop 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: bigtop
  name: spark-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-role-binding
  namespace: bigtop
subjects:
- kind: ServiceAccount
  name: spark
  namespace: bigtop
roleRef:
  kind: Role
  name: spark-role
  apiGroup: rbac.authorization.k8s.io
