# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure("2") do |config|
  vmbox = "vagrant-fedora19B"

  # Virtual Box implementation
  vmboxurl = "http://rhbd.s3-us-west-1.amazonaws.com/vagrant/fedora19B.box"

  #First node in the cluster.
  #HMaster
  config.vm.define :bigtop1 do |bigtop1|
  
  		# cachier plugin for faster install,
  		# see https://github.com/fgrehm/vagrant-cachier
        # bigtop1.cache.enable :yum
        
        bigtop1.vm.box = vmbox
        bigtop1.vm.box_url = vmboxurl
                
        bigtop1.vm.network :private_network, ip: "10.10.10.11"
        
        # bigtop1.vm.synced_folder "./config", "/vagrant"
        
        bigtop1.vm.hostname = "rs1"
        bigtop1.vm.provision :shell, :path => "provision.sh"
  end

  # Master node
  # config.vm.define :bigtop2 do |bigtop2|
  #       bigtop2.cache.enable :yum
  #       bigtop2.cache.auto_detect = true
  #       bigtop2.vm.box = vmbox
  #       bigtop2.vm.box_url = vmboxurl
  #       bigtop2.vm.host_name = "master"
  #       bigtop2.vm.network "private_network", ip: "10.10.10.12"
  #       bigtop2.vm.synced_folder "./config", "/vagrant"
  #       bigtop2.vm.provision "shell", path: "provision.sh"
  # end
 
end
