#!/usr/bin/python3

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import unittest
import re
import amulet
import subprocess

DEPLOY_TIMEOUT = 1800
CONFIG_TIMEOUT = 900


class TestBindClientPort(unittest.TestCase):
    """
    Test to verify that we can bind to listen for client connections
    on a specific interface.
    """

    @classmethod
    def setUpClass(cls):
        cls.d = amulet.Deployment(series='xenial')

        cls.d.add('zookeeper', charm='zookeeper', units=3)

        cls.d.setup(timeout=CONFIG_TIMEOUT)
        cls.d.sentry.wait(timeout=DEPLOY_TIMEOUT)
        cls.unit = cls.d.sentry['zookeeper'][0]

    def test_bind_port(self):
        """
        Test to verify that we update client port bindings successfully.

        """
        network_interface = None
        # Regular expression should handle interfaces in the format
        # eth[n], and in the format en[foo] (the "predicatble
        # interface names" in v197+ of systemd).
        ethernet_interface = re.compile('^e[thn]+.*')
        interfaces, _ = self.unit.run(
            "ifconfig -a | sed 's/[ \t].*//;/^$/d'")
        interfaces = interfaces.split()  # Splits on newlines
        for interface in interfaces:
            if ethernet_interface.match(interface):
                network_interface = interface
                break

        if network_interface is None:
            raise Exception(
                "Could not find any interface on the unit that matched my "
                "criteria.")
        # self.d.configure broken due to change in juju api. TODO:
        # switch this out when fixed.
        subprocess.check_call(
            ['juju', 'config', 'zookeeper', 'network_interface={}'.format(
                network_interface)])
        #self.d.configure('zookeeper', {'network_interface': network_interface})
        self.d.sentry.wait_for_messages(
            {'zookeeper': 'updating network interface'}, timeout=CONFIG_TIMEOUT)
        self.d.sentry.wait_for_messages(
            {'zookeeper': 'ready (3 zk nodes)'}, timeout=CONFIG_TIMEOUT)
        ret = self.unit.run(
            'grep clientPortAddress /etc/zookeeper/conf/zoo.cfg')[0]
        matcher = re.compile(
            "^clientPortAddress=\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}.*")

        self.assertTrue(matcher.match(ret))

        # Verify that smoke tests still run
        smk_uuid = self.unit.action_do("smoke-test")
        result = self.d.action_fetch(smk_uuid, full_output=True)
        # zookeeper smoke-test sets outcome=success on success
        if (result['outcome'] != "success"):
            error = "Zookeeper smoke-test failed"
            amulet.raise_status(amulet.FAIL, msg=error)

    @unittest.skip(
        'Broken handling of 0.0.0.0 bindings upstream, in Zookeeper project.')
    def test_reset_bindings(self):
        """
        Verify that we can reset the client port bindings to 0.0.0.0

        """
        self.d.configure('zookeeper', {'network_interface': '0.0.0.0'})
        self.d.sentry.wait_for_messages(
            {'zookeeper': 'updating network interface'}, timeout=CONFIG_TIMEOUT)
        self.d.sentry.wait_for_messages(
            {'zookeeper': 'ready (3 zk nodes)'}, timeout=CONFIG_TIMEOUT)
        ret = self.unit.run(
            'grep clientPortAddress /etc/zookeeper/conf/zoo.cfg')[0]

        matcher = re.compile("^clientPortAddress=0\.0\.0\.0.*")
        self.assertTrue(matcher.match(ret))

        # Verify that smoke tests still run
        smk_uuid = self.unit.action_do("smoke-test")
        output = self.d.action_fetch(smk_uuid, full_output=True)
        assert "completed" in output['status']


if __name__ == '__main__':
    unittest.main()
