#!/usr/local/sbin/charm-env bash

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
set -e

for line in "$(crontab -lu ubuntu | grep '# action: ')"; do
    if [[ -n "$line" ]]; then
        # the action uuid is after the 'action:' comment
        action_id=$(echo "$line" | sed -e 's/.* # action: //')

        # the actual job is everything before the 'action:' comment
        job_code=$(echo "$line" | sed -e 's/ # action: .*//')

        # show the people what they want
        action-set job.$action_id="$job_code"
    fi
done
