#!/usr/local/sbin/charm-env bash

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
set -e

if ! charms.reactive is_state 'spark.started'; then
    action-set outcome="failure"
    action-fail 'Spark not yet ready'
    exit 1
fi

job="$(action-get job)"
job_args="$(action-get job-args)"
options="$(action-get options)"
cron="$(action-get cron)"

job_code=". /etc/environment ; spark-submit ${options} ${job} ${job_args}"
action-set job-code="$job_code"

if [[ -z "$cron" ]]; then
    su ubuntu -c "$job_code"
else
    juju-log "Scheduling job with ID $JUJU_ACTION_UUID"
    action-set action-id="$JUJU_ACTION_UUID"
    job_line="$cron $job_code # action: $JUJU_ACTION_UUID"

    # if we dont have a crontab, make an empty one
    crontab -lu ubuntu > /dev/null || echo -n | crontab -u ubuntu -

    # append our job to then end of any existing crontab
    (crontab -lu ubuntu; echo "$job_line") | crontab -u ubuntu -
fi
