options:
  network_interface:
    default: ""
    type: string
    description: |
      Network interface to bind the Zookeeper client port to. Defaults
      to accepting connections on all interfaces. Accepts either the
      name of an interface (e.g., 'eth0'), or a CIDR range. If the
      latter, we\'ll bind to the first interface that we find with an
      IP address in that range.
  autopurge_purge_interval:
    default: "24"
    type: string
    description: |
      The time interval in hours for which the purge task has to be
      triggered. Set to a positive integer (1 and above) to enable
      the auto purging. Defaults to 24.
  autopurge_snap_retain_count:
    default: "3"
    type: string
    description: |
      When enabled, ZooKeeper auto purge feature retains the
      snapRetainCount most recent snapshots and the corresponding
      transaction logs in the dataDir and dataLogDir respectively
      and deletes the rest. Defaults to 3. Minimum value is 3.
  nagios_context:
    default: "juju"
    type: string
    description: |
      Used by the nrpe subordinate charms.
      A string that will be prepended to instance name to set the host name
      in nagios. So for instance the hostname would be something like:
          juju-myservice-0
      If you're running multiple environments with the same services in them
      this allows you to differentiate between them.
  nagios_servicegroups:
    default: ""
    type: string
    description: |
      A comma-separated list of nagios servicegroups.
      If left empty, the nagios_context will be used as the servicegroup
