#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex
. `dirname $0`/bigtop.bom


rm -rf desktop/core/ext-py/pyopenssl desktop/core/ext-py/cryptography-1.3.1
wget https://github.com/pyca/cryptography/archive/1.8.2.tar.gz
tar -xz -C desktop/core/ext-py/ -f 1.8.2.tar.gz
rm -f 1.8.2.tar.gz
wget https://pypi.python.org/packages/3b/15/a5d90ab1a41075e8f0fae334f13452549528f82142b3b9d0c9d86ab7178c/pyOpenSSL-17.5.0.tar.gz
tar -xz -C desktop/core/ext-py/ -f pyOpenSSL-17.5.0.tar.gz
rm -f pyOpenSSL-17.5.0.tar.gz
wget https://pypi.python.org/packages/c6/70/bb32913de251017e266c5114d0a645f262fb10ebc9bf6de894966d124e35/packaging-16.8.tar.gz
tar -xz -C desktop/core/ext-py/ -f packaging-16.8.tar.gz
rm -f packaging-16.8.tar.gz

#FIXME: this needs to be fixed upstream
sed -i -e "s#${FULL_VERSION}-SNAPSHOT#${FULL_VERSION}#g" `grep -lR ${FULL_VERSION}-SNAPSHOT .`
export PATH=$PATH:/usr/lib/mit/bin

make MAVEN_VERSION=${HUE_VERSION} apps docs locales

# Make the entire tree relocatable
bash tools/relocatable.sh
