#!/usr/local/sbin/charm-env python3

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import sys
sys.path.append('lib')

from charmhelpers.core import hookenv  # noqa: E402
from charms.layer.apache_bigtop_base import Bigtop  # noqa: E402
from charms.reactive import is_state  # noqa: E402


def fail(msg):
    hookenv.action_set({'outcome': 'failure'})
    hookenv.action_fail(msg)
    sys.exit()


if not is_state('apache-bigtop-resourcemanager.ready'):
    fail('Charm is not yet ready to run the Bigtop smoke test(s)')

# Bigtop smoke test components
smoke_components = ['yarn']

# Env required by test components
smoke_env = {
    'HADOOP_CONF_DIR': '/etc/hadoop/conf',
}

bigtop = Bigtop()
result = bigtop.run_smoke_tests(smoke_components, smoke_env)
if result == 'success':
    hookenv.action_set({'outcome': 'success'})
else:
    fail('{} smoke tests failed with: {}'.format(smoke_components, result))
