#!/usr/local/sbin/charm-env bash

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

if ! charms.reactive is_state 'hbase.installed'; then
    action-fail 'HBase is not yet ready'
    exit
fi

MROWS=`action-get mrows`

# create dir to store results
RUN=`date +%s`
RESULT_DIR=/opt/hbase-perf-results
RESULT_LOG=${RESULT_DIR}/${RUN}.log
mkdir -p ${RESULT_DIR}
chown -R hbase:hbase ${RESULT_DIR}

benchmark-start
START=`date +%s`
su hbase << EOF
echo 'Running performance evaluation'
hbase org.apache.hadoop.hbase.PerformanceEvaluation --nomapred randomWrite ${MROWS} &> ${RESULT_LOG}
EOF
STOP=`date +%s`
benchmark-finish

DURATION=`expr $STOP - $START`
benchmark-composite "${DURATION}" 'secs' 'asc'
action-set meta.raw=${RESULT_LOG}
action-set outcome="success"
