#!/usr/local/sbin/charm-env python3

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import sys

from charmhelpers.core import host, hookenv
from charms.reactive import is_state


def fail(msg):
    hookenv.action_fail(msg)
    sys.exit()


if not is_state('hbase.installed'):
    fail('HBase is not yet ready')

if not host.service_available('hbase-regionserver') or \
   not host.service_available('hbase-thrift'):
    fail('Could not find hbase-regionserver/hbase-thrift init services')

host.service_stop('hbase-regionserver')
host.service_stop('hbase-thrift')
