#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

. `dirname $0`/bigtop.bom

mvn clean install \
  -DjavaVersion=${JDK_VERSION} \
  -Dvers.hadoop2=${HADOOP_VERSION} \
  -Dvers.hbase2=${HBASE_VERSION} \
  -Dvers.flume=${FLUME_VERSION} \
  -Dvers.spark=${SPARK_VERSION} \
  -Dvers.crunch=${CRUNCH_VERSION} \
  -DskipTests -Dmaven.repo.local=${HOME}/.m2/repository "$@"

rm -rf build

mkdir -p build/kite-${KITE_VERSION}/{bin,lib}

# Kite Data
cp kite-data/kite-*/target/kite-*.jar build/kite-${KITE_VERSION}/lib
# Kite Tools
cp kite-tools-parent/kite-tools/target/kite-dataset build/kite-${KITE_VERSION}/bin/
cp kite-tools-parent/kite-tools/target/kite-*.jar build/kite-${KITE_VERSION}/lib/

# Kite Morphlines
cp kite-morphlines/kite-morphlines-all/target/lib/* build/kite-${KITE_VERSION}/lib/

# Kite Maven plugin
cp kite-maven-plugin/target/kite-*.jar build/kite-${KITE_VERSION}/lib/




