#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex


. `dirname $0`/bigtop.bom
mkdir trino
# Apply the Puppet manifest to download and extract JDK
sudo puppet apply jdk17_download.pp
# Set JAVA_HOME for this session to the JDK downloaded by the Puppet manifest
export JAVA_HOME=/opt/jdk-17.0.2
echo JAVA_HOME=`pwd`/`ls | grep "jdk-*"` >> ~/.bash_profile
source ~/.bash_profile

# Setting versions for trino build
mvn clean -pl !plugin/trino-kafka,!testing/trino-benchto-benchmarks,!docs install -DskipTests -Dcheckstyle.skipExec -Dmaven.wagon.http.ssl.allowall=true
sed -i '$ d' ~/.bash_profile
source ~/.bash_profile
rm -rf `pwd`/`ls | grep "jdk-*"`

mkdir -p build/trino
mkdir -p build/trino-cli

# Server
tar -C build/trino --strip-components=1 -xzf core/trino-server/target/*.tar.gz
# CLI
cp -ra client/trino-cli/target/*-executable.jar build/trino-cli/trino
