/usr/bin/checksum
/usr/bin/dirtree_creator
/usr/bin/dtokentest
/usr/bin/qfslogger
/usr/bin/rand-sfmt
/usr/bin/rebalanceexecutor
/usr/bin/rebalanceplanner
/usr/bin/replicachecker
/usr/bin/requestparser
/usr/bin/sortedhash
/usr/bin/sslfiltertest
/usr/bin/stlset

/usr/include

/usr/lib/qfs/libJerasure.a
/usr/lib/qfs/libgf_complete.a
/usr/lib/qfs/libqfs_client.a
/usr/lib/qfs/libqfs_common.a
/usr/lib/qfs/libqfs_emulator.a
/usr/lib/qfs/libqfs_io.a
/usr/lib/qfs/libqfs_meta.a
/usr/lib/qfs/libqfs_qcdio.a
/usr/lib/qfs/libqfs_qcrs.a
/usr/lib/qfs/libqfs_tools.a
/usr/lib/qfs/libqfsc.a
/usr/lib/qfs/libqfskrb.a
