#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

. `dirname $0`/bigtop.bom

export MAVEN_OPTS="-Xmx512M"

sed -i '/asm-all/{n;s/4.2/5.0.2/}' modules/hadoop/pom.xml

# Fix JVM_OPTS variable unbound issue when starting ignite-hadoop-service
sed -i "s/JVM_OPTS/\{JVM_OPTS\:\-\}/g" bin/include/service.sh
sed -i "s/^.*{JVM_OPTS:-}=.*$/JVM_OPTS=\"\$\{JVM_OPTS\:\-\} \-Xms1g \-Xmx1g \-server \-XX\:\+AggressiveOpts \-XX\:MaxPermSize\=512m\"/" bin/include/service.sh

cd ipc/shmem
# patch and build it
sed -i 's/\&ipcData->closed\,/(char *)\&ipcData->closed\,/' igniteshmem/org_apache_ignite_internal_util_ipc_shmem_IpcSharedMemoryUtils.cpp
./configure && make
# create layout
mkdir -p META-INF/native/linux64
cp ./igniteshmem/.libs/libigniteshmem.so META-INF/native/linux64/libigniteshmem.so
# pack and install
jar cf ignite-shmem-1.0.0.jar META-INF
mvn install:install-file -Dfile=ignite-shmem-1.0.0.jar -DgroupId=org.gridgain -DartifactId=ignite-shmem -Dversion=1.0.0 -Dpackaging=jar -DcreateChecksum=true
# clean up
rm -rf META-INF
cd -

mvn clean install -Pall-java,all-scala -DskipTests -Dhadoop.version=$HADOOP_VERSION
mvn initialize -Prelease -Dignite.edition=apache-ignite-hadoop
