#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

. `dirname $0`/bigtop.bom

export MAVEN_OPTS="-Xmx1536m -Xms256m"

sed -i -e \
's#<artifactId>asynchbase</artifactId>#<artifactId>asynchbase</artifactId>\n<exclusions>\n<exclusion>\n<groupId>org.apache.zookeeper</groupId>\n<artifactId>zookeeper</artifactId>\n</exclusion>\n</exclusions>#' flume-ng-sinks/flume-ng-hbase-sink/pom.xml


# The following is weird, but true: yes *hadoop*.profile is hbase-98
# This profile will activate hadoop2.version as the relevant property
# and will also make us specify hbase version with -hadoop2 prefix
mvn -DskipTests  \
  -Dhadoop.version=${HADOOP_VERSION} \
  -Dhbase.version=${HBASE_VERSION} \
  -Dhive.version=${HIVE_VERSION} \
  -Dkafka.version=${KAFKA_VERSION} \
  -Dzookeeper.version=${ZOOKEEPER_VERSION} \
  clean install "$@"
