#!/bin/sh
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

. `dirname $0`/bigtop.bom


mvn clean compile package install \
        -DskipTests=true       \
        -Dcheckstyle.skip=true \
        -Djacoco.skip=true     \
        -Dpmd.skip=true        \
        -Drat.skip=true        \
        -Dspotbugs.skip=true   \
        -Denunciate.skip=true  \
        -Dhadoop.version=${HADOOP_VERSION} \
        -Dhbase.version=${HBASE_VERSION}   \
        -Dhive.version=${HIVE_VERSION}     \
        -Dkafka.version=${KAFKA_VERSION}   \
        -Dsolr.version=${SOLR_VERSION}     \
        -Dzookeeper.version=${ZOOKEEPER_VERSION} \
        "$@"

mkdir build
for f in target/ranger*.tar.gz
do
	tar -C build -xf ${f}
done
