#!/bin/bash
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Initialize HDFS
#
# chkconfig: 345 90 15
# description: Hadoop nodemanager
#
### BEGIN INIT INFO
# Provides:          bigtop-init-hdfs
# Short-Description: Initialize HDFS directories used by Yarn
# Default-Start:     3 4 5
# Default-Stop:      0 1 2 6
# Required-Start:    $syslog $remote_fs hadoop-hdfs-namenode
# Required-Stop:     $syslog $remote_fs
# Should-Start:
# Should-Stop:
### END INIT INFO

. /lib/lsb/init-functions

# Ensure this is run only once 
FIRST_EXECUTION_LOCK="/var/lib/bigtop-init-hdfs"

RETVAL=0

start() {
  log_success_msg "Initializing HDFS"
	
  if [ ! -e "${FIRST_EXECUTION_LOCK}" ]; then
    /usr/lib/hadoop/libexec/init-hdfs.sh
	 touch "${FIRST_EXECUTION_LOCK}"
  fi
  RETVAL=$?
  return $RETVAL
}

service() {
  case "$1" in
    start)
      start
      ;;
    *)
      exit 0
  esac
}

service "$1"

exit $RETVAL
