#!/bin/bash

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

if hdfs dfs -stat /tmp/input/ &> /dev/null; then
    hdfs dfs -rm -r -skipTrash /tmp/input/ || true
fi

hdfs dfs -mkdir /tmp/input/
hdfs dfs -put resources/tiny_graph.txt /tmp/input/

if hdfs dfs -stat temp &> /dev/null; then
    hdfs dfs -rm -r -skipTrash temp || true
fi
if hdfs dfs -stat output &> /dev/null; then
    hdfs dfs -rm -r -skipTrash output || true
fi

hadoop jar /usr/lib/giraph/giraph-core.jar org.apache.giraph.GiraphRunner -libjars ${LIB_JARS} org.apache.giraph.examples.SimplePageRankComputation -vif org.apache.giraph.io.formats.JsonLongDoubleFloatDoubleVertexInputFormat -vip /tmp/input/tiny_graph.txt -mc org.apache.giraph.examples.SimplePageRankComputation\$SimplePageRankMasterCompute -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op output -w 1 -ca mapred.job.tracker=empty yarn.log-aggregation-enable=true

#hadoop jar resources/giraph-examples-1.1.0.jar org.apache.giraph.GiraphRunner org.apache.giraph.examples.SimpleShortestPathsComputation -vif org.apache.giraph.io.formats.JsonLongDoubleFloatDoubleVertexInputFormat -vip /tmp/input/tiny_graph.txt -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /tmp/output/shortestpaths -w 1
