# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# -*- mode: ruby -*-
# vi: set ft=ruby :

require "yaml"

_config = YAML.load(File.open(File.join(File.dirname(__FILE__), "../vagrantconfig.yaml"), File::RDONLY).read)
CONF = _config

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "boot2docker" do |node|
    node.vm.box = "yungsang/boot2docker"
    node.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--memory", CONF["boot2docker"]["memory_size"]]
      vb.customize ['modifyvm', :id, '--cpus', CONF["boot2docker"]['number_cpus']]
    end
    node.vm.network "forwarded_port", host: CONF["namenode_ui_port"], guest: 50070
    node.vm.network "forwarded_port", host: CONF["yarn_ui_port"], guest: 8088
    node.vm.network "forwarded_port", host: CONF["hbase_ui_port"], guest: 60010
  end

end
