#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

<<<<<<<< HEAD:provisioner/docker/config_fedora-38.yaml
docker:
        memory_limit: "4g"
        image: "bigtop/puppet:trunk-fedora-38"

repo: "http://repos.bigtop.apache.org/releases/3.3.0/fedora/38/$basearch"
distro: centos
components: [hdfs, yarn, mapreduce]
enable_local_repo: false
smoke_test_components: [hdfs, yarn, mapreduce]
========
set -ex

. `dirname $0`/bigtop.bom

./build/make-distribution.sh --sbt-enabled --release
>>>>>>>> udh3:bigtop-packages/src/common/celeborn/do-component-build
