#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

. `dirname $0`/bigtop.bom

LIVY_BUILD_OPTS="-Drat.skip=true \
                 -DskipTests \
                 -Dskip=true \
                 -DskipITs=true \
                 -Dscala-${SCALA_VERSION%.*}.version=${SCALA_VERSION} \
                 -Dscala.binary.version=${SCALA_VERSION%.*} \
                 -Dscala.version=${SCALA_VERSION} \
                 -Dzookeeper.version=${ZOOKEEPER_VERSION} \
                 -Dhadoop.version=${HADOOP_VERSION} \
                 -Dhadoop.major-minor.version=${HADOOP_VERSION%%.*} \
                 -Dhive.version=${HIVE_VERSION} \
                 -Dspark.scala-${SCALA_VERSION%.*}.version=${SPARK_VERSION} \
                 -Dspark.version=${SPARK_VERSION} \
                 -Pspark3"

mvn install $LIVY_BUILD_OPTS "$@"

unzip assembly/target/apache-livy-$LIVY_VERSION-incubating_${SCALA_VERSION%.*}-bin.zip
mv apache-livy-$LIVY_VERSION-incubating_${SCALA_VERSION%.*}-bin build
