#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

. `dirname $0`/bigtop.bom

sed -i -e '/<dependency org="org.apache.pig"/s# rev=[^ >][^ >]*# rev="'$PIG_VERSION'"#' ivy.xml
sed -i -e 's/\(<settings defaultResolver="ivyrep"\/>\)/\1\n<property name="m2-pattern" value="${user.home}\/.m2\/repository\/[organisation]\/[module]\/[revision]\/[module]-[revision](-[classifier]).[ext]" override="false"\/>/' ivysettings.xml
sed -i -e 's/\(^ *<ibiblio\)/    <filesystem name="local-maven2" m2compatible="true">\n      <artifact pattern="${m2-pattern}"\/>\n      <ivy pattern="${m2-pattern}"\/>\n    <\/filesystem>\n\1/' ivysettings.xml

ant jar -Dversion=$DATAFU_VERSION "$@"

# Install artifacts into the local Maven cache
mvn install:install-file -DcreateChecksum=true -DgroupId=com.linkedin.datafu -DartifactId=datafu -Dversion=$DATAFU_VERSION -Dpackaging=jar -Dfile=dist/datafu-$DATAFU_VERSION.jar

