#!/bin/sh
# postinst script for zookeeper

set -e

case "$1" in
    configure)
        # Install config alternatives
        update-alternatives  --install /etc/zookeeper/conf hadoop-zookeeper-conf /etc/zookeeper/conf.dist 30
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#
