#!/usr/local/sbin/charm-env python3

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import kafkautils
import subprocess

from charmhelpers.core import hookenv, host
from charms.layer.apache_bigtop_base import get_layer_opts
from charms.reactive import is_state
from jujubigdata import utils


if not is_state('kafka.started'):
    kafkautils.fail('Kafka service not yet ready')


# Grab the business
topic_name = hookenv.action_get('topic')
data = hookenv.action_get('data')

# Write to the topic if kafka is running
if host.service_available('kafka-server') and host.service_running('kafka-server'):
    host = subprocess.check_output(['hostname', '-s']).decode('utf8').strip()
    port = get_layer_opts().port('kafka')
    zookeepers = kafkautils.get_zookeepers()
    try:
        output = utils.run_as('kafka', 'kafka-console-producer.sh',
                              '--broker-list', '{}:{}'.format(host, port),
                              '--topic', topic_name,
                              capture_output=True,
                              input=bytes(data, 'UTF-8'))
    except subprocess.CalledProcessError as e:
        kafkautils.fail('Kafka command failed: {}'.format(e.output))
    else:
        hookenv.action_set({'raw': output})
        hookenv.action_set({'outcome': 'success'})
else:
    kafkautils.fail('kafka-server service is not running')
