---
### This is very important to make sure this file doesn't contain any TAB
### symbols instead of spaces: the hiera YAML parser will choke to death with
### uncomprehensive error message and you'll waste a lot of time debugging it.
bigtop::hadoop_head_node: "head.node.fqdn"
#bigtop::standby_head_node: "standby.head.node.fqdn"

hadoop::hadoop_storage_dirs:
  - /data/1
  - /data/2
  - /data/3
  - /data/4

#hadoop_cluster_node::cluster_components:
#  - crunch
#  - flume
#  - giraph
#  - ignite_hadoop
#  - hbase
#  - hcat
#  - hive
#  - httpfs
#  - hue
#  - mahout
#  - mapred-app
#  - oozie
#  - pig
#  - solrcloud
#  - spark
#  - sqoop
#  - sqoop2
#  - tachyon
#  - tez
#  - yarn
#  - zookeeper
#  - ycsb

#bigtop::roles_enabled: false

#bigtop::jdk_package_name: "openjdk-7-jre-headless"
#bigtop::bigtop_repo_uri: "http://mirror.example.com/path/to/mirror/"
