---
### This is very important to make sure this file doesn't contain any TAB
### symbols instead of spaces: the hiera YAML parser will choke to death with
### uncomprehensive error message and you'll waste a lot of time debugging it.
bigtop::hadoop_head_node: "head.node.fqdn"
#bigtop::standby_head_node: "standby.head.node.fqdn"

hadoop::hadoop_storage_dirs:
  - /data/1
  - /data/2
  - /data/3
  - /data/4

#hadoop_cluster_node::cluster_components:
#  - alluxio
#  - flink
#  - gpdb
#  - hbase
#  - hcat
#  - hive
#  - httpfs
#  - knox
#  - mapred-app
#  - solr
#  - spark
#  - spark-standalone
#  - tez
#  - yarn
#  - zookeeper

#bigtop::roles_enabled: false

## You can specify one (or more) repositories. It is convenient if
## you provide hotfix repo separately from the stable release, etc.
#bigtop::bigtop_repo_uri:
#   - "http://mirror1.example.com/path/to/mirror/"
#   - "http://mirror2.example.com/path/to/mirror/"
