#!/usr/bin/env bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Add files to BIGTOP_CLASSPATH and they will be prepended to the contents of /var/lib/bigtop
BIGTOP_DEFAULTS_DIR=${BIGTOP_DEFAULTS_DIR-/etc/default}
[ -n "${BIGTOP_DEFAULTS_DIR}" -a -r ${BIGTOP_DEFAULTS_DIR}/bigtop-utils ] && . ${BIGTOP_DEFAULTS_DIR}/bigtop-utils

# Overriding this is not recommended because it has had to be hard-coded in
# properties files for components that use bigtop-tomcat
BIGTOP_CLASSPATH_DIR=/var/lib/bigtop

# Create a string suitable for inclusion in CLASSPATH
# for components that can use it in their environment
for file in $BIGTOP_CLASSPATH_DIR/*.jar; do
    if [ -z "$BIGTOP_CLASSPATH" ]; then
        BIGTOP_CLASSPATH="$file"
    else
        BIGTOP_CLASSPATH="$BIGTOP_CLASSPATH:$file"
    fi
done
export BIGTOP_CLASSPATH
