#!/usr/bin/env bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# Override python3 in the file below if you want to disable
# automatic python3 detection
BIGTOP_DEFAULTS_DIR=${BIGTOP_DEFAULTS_DIR-/etc/default}
[ -n "${BIGTOP_DEFAULTS_DIR}" -a -r ${BIGTOP_DEFAULTS_DIR}/bigtop-utils ] && . ${BIGTOP_DEFAULTS_DIR}/bigtop-utils

PYTHON3_PATH_CANDIDATES=(
    '/usr/bin/python3'
    '/opt/python3/bin/python3'
    '/usr/lib/python3/bin/python3'
)

# attempt to find python3
if [ -z "${PYTHON3_PATH}" ]; then
  for candidate in ${PYTHON3_PATH_CANDIDATES[@]} ; do
    if [ -e ${candidate} ]; then
      export PYTHON3_PATH=${candidate}
      break
    fi
  done
fi
