#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex
. `dirname $0`/bigtop.bom

mvn -DskipTests \
    -Dhadoop.version=$HADOOP_VERSION  \
    -Dhbase.version=$HBASE_VERSION  \
    -Dhbase.profile=${HBASE_VERSION%.*} \
    clean install "$@"
rm -rf build
mkdir build

tar -C build --strip-components=1 -xzf phoenix-assembly/target/phoenix-hbase-${HBASE_VERSION%.*}-${PHOENIX_VERSION}-bin.tar.gz