#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

. `dirname ${0}`/bigtop.bom

cat <<__EOT__ >> ivy/libraries.properties

hbase95.version=$HBASE_VERSION
hive.version=$HIVE_VERSION
zookeeper.version=$ZOOKEEPER_VERSION
hadoop-common.version=$HADOOP_VERSION
hadoop-hdfs.version=$HADOOP_VERSION
hadoop-mapreduce.version=$HADOOP_VERSION
__EOT__

# Respect FORREST_HOME if defined and valid (assume users knows what they are doing), else fallback to creating our own home.
if [ -z ${FORREST_HOME-} ] || [ ! -d $FORREST_HOME ]; then
  BIGTOP_FORREST_VER=${BIGTOP_FORREST_VER:-0.9}
  BIGTOP_FORREST_MD5=${BIGTOP_FORREST_MD5:-ea58a078e3861d4dfc8bf3296a53a5f8}
  BIGTOP_FORREST_TAR=apache-forrest-${BIGTOP_FORREST_VER}.tar.gz

  if [ ! -z ${LOCAL_DOWNLOADS_DIR-} ] \
      && [ -f $LOCAL_DOWNLOADS_DIR/forrest/$BIGTOP_FORREST_TAR ]; then
    forrest_tar_path=$LOCAL_DOWNLOADS_DIR/forrest/$BIGTOP_FORREST_TAR
  else
    forrest_dir=$HOME/.m2/repository/apache-forrest
    forrest_tar_path=$forrest_dir/$BIGTOP_FORREST_TAR
    (
      mkdir -p $forrest_dir ;
      # since -O and -N cannot be used together, work around this issue by changing dir first.
      cd $forrest_dir ;
      /usr/bin/wget -N https://archive.apache.org/dist/forrest/$BIGTOP_FORREST_VER/$BIGTOP_FORREST_TAR
    )
  fi

  forrest_tar_md5=$(md5sum $forrest_tar_path | cut -d" " -f1)
  if [ $forrest_tar_md5 != $BIGTOP_FORREST_MD5 ]; then
      echo "ERROR: MD5: $forrest_tar_md5 of $forrest_tar_path is not matching expected MD5: $BIGTOP_FORREST_MD5"
      exit 1
  fi
  tar xf $forrest_tar_path
  export FORREST_HOME=`pwd`/apache-forrest-${BIGTOP_FORREST_VER}
fi

BUILD_OPTS="-Djavac.version=${JDK_VERSION} -Dforrest.home=${FORREST_HOME} -Dversion=${PIG_VERSION} -Dhadoopversion=23"

# FIXME: there's a weird synchronization issue between ivy and Maven caches wrt. jetty
# If we don't do the following the build fails with (note zip instead of jar):
# [ivy:resolve]                ::::::::::::::::::::::::::::::::::::::::::::::
# [ivy:resolve]                ::              FAILED DOWNLOADS            ::
# [ivy:resolve]                :: ^ see resolution messages for details  ^ ::
# [ivy:resolve]                ::::::::::::::::::::::::::::::::::::::::::::::
# [ivy:resolve]                :: org.mortbay.jetty#jetty;6.1.26!jetty.zip
# [ivy:resolve]                ::::::::::::::::::::::::::::::::::::::::::::::
for h in ${HOME} `mvn help:system | grep '^user.home=' | cut -f2 -d=` ; do
  rm -rf ${h}/.ivy2/cache/*jetty ${h}/.m2/repository/org/mortbay ${h}/.m2/repository/org/eclipse/jetty
done


echo "forrest.maxmemory=256m" >> src/docs/forrest.properties

export ANT_OPTS="-Xmx4096m"
ant $BUILD_OPTS clean published pigunit-jar smoketests-jar javadoc "$@"
for build_file in contrib/piggybank/java/build.xml ; do
  ant $BUILD_OPTS -buildfile $build_file clean jar "$@"
done
ant $BUILD_OPTS tar "$@"
